version: "2.0"

services:
        api:
                container_name: api
				depends_on:
                        - db
                hostname: api
                image: intellique/api:testing
                volumes:
                        - data-admin:/var/lib/storiqone-backend
                        - data-vol:/var/www/nextcloud/data

        daemon:
                container_name: daemon
                depends_on:
                        - db
                hostname: daemon
                image: intellique/daemon:testing
                volumes:
                        - data-vol:/var/www/nextcloud/data

        db:
                container_name: db
                hostname: db
                image: intellique/database:testing

        nextcloud:
                container_name: nextcloud
                depends_on:
                        - db
                image: intellique/nextcloud:testing
                volumes:
                        - data-admin:/var/lib/storiqone-backend:ro
                        - data-vol:/var/www/nextcloud/data

        proxy:
                container_name: proxy
                depends_on:
                        - api
                        - nextcloud
                        - webui
                image: intellique/haproxy:testing
                ports:
                        - "80:80"

        webui:
                container_name: webui
                depends_on:
                        - api
                hostname: webui
                image: intellique/webui:testing

volumes:
        data-admin:
        data-vol:
